/**************************************************************************************************/

/*
* File: Dependencie.h
* Author: Miguel A. Garcia
* NetID: magarcia1
* Assignment #: 5
* Date: December/10/2014
*
* Description: Street.h contains the class declaration of a class named street. The STREETS section lists
* all streets in the map. Every street has four properties startId, endId, minTravelTime, and maxTravelTime.
* The properties startId and endId represent the two waypoints linked by this street (in that direction).
* The properties minTravelTime and maxTravelTime represent the range of travel time (in minutes) that
* this street could take.
*
*/

/**************************************************************************************************/

#ifndef DEPENDENCIE_H
#define DEPENDENCIE_H

#include <vector>
#include <string>

//Instead of including a Waypoints.h here, we just used tell the compiler "it's a class, don't worry
//about it." This is an example of the usefulness of Forward Declaration.
class Component;

class Dependencie{
public:
	//only this Dependencie (or edge) needs to be created
	Dependencie(Component* adjComponent);
	Component* getAdjComponent() const { return this->adjComponent; }
	//rest of the big 4 are auto-generated by the compiler
	void setStartId(int startId){ this->startId = startId; }
	double getStartId() const { return this->startId; }

	void setEndId(int endId){ this->endId = endId; }
	double getEndId() const { return this->endId; }

private:
	//to whom do I connect?
	Component* adjComponent;
	string name;
	string sizeSpec;
	string type;
	int startId;
	int endId
	bool signedNum;

};

#endif

/***********************************************************************/